db:
  image: mongo
  ports:
    - "27017:27017"

app:
  build: .
  command: npm start
  volumes:
    - .:/usr/src/app
    - /usr/src/app/node_modules
  ports:
    - "8080:5465"
  links:
    - db
  environment:
    MONGODB: mongodb://db:27017/brigadehub-suite
    GITHUB_ID:
    GITHUB_SECRET:
